### ISSUE TITLE
MapGameType question

### ISSUE THREAD

**Issue by marciii** [uakfdotb/ghostpp#13]
Hi,

this one is not really an issue, more like a question regarding the mapgametype:
The game list is overloaded. But there's a certain reserved value (49161), which only works for officially signed blizzard maps and which makes the game visible on top of the list.
So far so good. But I still have a problem: When I use this value in the ghost.cfg, it doesn't make any difference (I also tried some debug output, the function GetMapGameType() in the map.cpp overwrites this value). My second try was to hardcode it (at the end of the GetMapGameType()-function) and just use "GameType = 49161;". However this results in a "failed to authorize the map" error in the wc3 client.
Is there any workaround to fix that?

Cheers

**Comment by uakfdotb** [comment]
Overridden map game type -- are you setting bot_mapgametype in ghost.cfg? It shouldn't be overridden, the code looks like this (bnet.cpp):

	uint32_t MapGameType = map->GetMapGameType( );
	MapGameType |= MAPGAMETYPE_UNKNOWN0;
	//Apply overwrite if not equal to 0
	MapGameType = ( m_GHost->m_MapGameType != 0 ) ? MapGameType : m_GHost->m_MapGameType;

	if( state == GAME_PRIVATE )
		MapGameType |= MAPGAMETYPE_PRIVATEGAME;

So initially MapGameType is set based on the map, but if m_GHost->m_MapGameType is nonzero, then m_GHost->m_MapGameType is used.

It might be useful to debug a bit what caused the overriding problem since that may be related to the second issue. You could add a CONSOLE_Print statement after the code above to print MapGameType, m_GHost->m_MapGameType, and map->GetMapGameType( ).

Note: you may want to convert the number to binary so you can see exactly what flags are getting set. You can just google "XYZ in binary".

For map authorized error, one way to debug it would be to see what the map game type reported by actual WC3 client is. So you run Wireshark, host the map in WC3 client, and then look for the SID_STARTADVEX3 TCP packets, which should start with 0xFF (header constant) and then 0x1C (SID_STARTADVEX3).

Another thing to check is map_path should be something like Maps\(2)BootyBay.w3m; it should not be in Maps\Download, and should use backslashes.

Also, do you get "failed to authorize the map" if you use a map configuration file like this, without overriding the map game type?

	map_path = Maps\(2)BootyBay.w3m
	map_localpath = (2)BootyBay.w3m
	map_options = 4

	# blizzard maker
	map_filter_maker = 2

	# melee map
	map_filter_type = 1

Note that the map_filter_maker option makes GHost++ automatically compute a map game type that includes the (1 << 14) MAPGAMETYPE_MAKERBLIZZARD flag, which is probably the flag in the map game type that makes it show up more often (perhaps gets put in a different bucket of games, and shows up just because so few games with Blizzard maps are being hosted).

**Comment by marciii** [comment]
Okay it is solved now. My issue was the structure of the maps directory. Apparently it has to be the exact same as it is in the wc3 installation directory. Then the players are able to join and stay - the "failed to authorize the map" error doesn't appear anymore.
But it's probably still useful to swap the parameters in line 2281, then the bot applies what is written in the ghost.cfg.

**Comment by uakfdotb** [comment]
Ah oops... thanks for the fix (I committed it)!
