### ISSUE TITLE
Patch 1.30.2

### ISSUE THREAD

**Issue by marciii** [uakfdotb/ghostpp#20]
Hi,

since 1.30.2 is out and the network traffic will be encrypted and the hosting system is changed - is there still a chance to keep the bot running?

See details here:
https://us.battle.net/forums/en/bnet/topic/20769476896

**Comment by uakfdotb** [comment]
I tried to investigate the WC3<->Battle.net protocol with mitmproxy, but I wasn't even able to dump the HTTPS packets, WC3 seems to reject the certificate generated by mitmproxy even though I added the CA to Windows CA DB. It's possible I did something wrong, but I think WC3 has its own list of CAs.

So I'm not really sure how to go about investigating the protocol.

If they were to publish a bit of documentation on the protocol then I think it'd be possible to implement the update, but otherwise updating would need someone interested enough in WC3 who also has experience in reverse engineering.

Has anyone else had any luck with investigating this? I don't have much experience with this kind of thing so I could be on the completely wrong track.

**Comment by Stannnnn** [comment]
Are we even sure the protocol allows for hosting games ourselves still? It sounds like after the new update games are hosted on blizzard servers since port forwarding is no longer required. If that is the case then nothing we can do for hostbots?

**Comment by kirill-782** [comment]
It makes no sense to write a bot under official servers. small online, a lot of code

**Comment by uakfdotb** [comment]
> Are we even sure the protocol allows for hosting games ourselves still? It sounds like after the new update games are hosted on blizzard servers since port forwarding is no longer required. If that is the case then nothing we can do for hostbots?

I think it is possible in theory; if I understand correctly, the games are hosted by the player but the Blizzard server acts as a router so that port forwarding is not needed.

However, I read that someone on development team stated unequivocally that Blizzard intends to make it impossible for host bots to function any more. If that is Blizzard's stance, then there is no reason to work on this, since they could easily make an update that would break any progress.

**Comment by uakfdotb** [comment]
Here is the image, I think it's a discord conversation: https://image.prntscr.com/image/L2DRTDwVSJO9xlNCVeSPZw.png

Closing since WC3 development team unambiguously stated they want to make it impossible for host bots to function with 1.30.2 patch.

**Comment by kirill-782** [comment]
They dig their own grave. In the custom server on the server no one plays
